version: "3.9"

services:
  api:
    build: .
    container_name: simpleapp_c
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo #database
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
